import { farmland, getTime } from "../Constant";
import dayjs from "dayjs";

const minTime = dayjs().hour(8).minute(0).second(0);
const maxTime = dayjs().hour(22).minute(0).second(0);

export const initialValues = {
  propertyCode: "",
  propertyType: farmland,
  plotArea: "acre",
  plotLength: "",
  logo: "",
  plotBreadth: "",
  possessionStatus: "immediate",
  possessionDate: "",
  reraApproved: "No",
  price: "",
  pricePerSqft: "",
  negotiablePrice: "No",
  boundWallMade: "No",
  openSidesCount: "1",
  propertyDescription: "",
  city: "",
  locality: "",
  map: "",
  amenities: [],
  layoutMap: [],
  images: [],
  videos: "",
  plotShow: "",
  secondaryNum: "",
  availability: "",
  scheduledTime: "",
  possessionDate: "",
  totalAcre: "",
  propertyTitle: "",
  propertyStatus: "available",
  videoUrl: "",
  otherAmenities: [],
  heroImage: "",
  state: "",
  maintainanceBills: [],
  propertyPapers: [],
  totalArea: "",
  masterPlan: "",
  isPropertyPromoted: false,
  propertyAds: "",
  categoryId: "",
  sellerId: "",
  propertyApproval: "IN_Review",
  status: "publish",
  daysAvailiblity: "Weekdays",
  alldaysAvailable: true,
  from: getTime(minTime),
  to: getTime(maxTime),
  priceMax: "",
  minArea: "",
  maxArea: "",
  pricePerMeter: "",
  pricePerYard: "",
  areaType: "Sq Ft",
  userInput: false,
  broucher: "",
  maintainaceOfYears: "",
  manageFarms: false,
  bedrooms: "",
  bathrooms: "",
  balconies: "",
  days: [],
  documentName: "",
  documentFile: "",
  buildUpArea: "",
  floorDetails: "",
  ageOfProperty: "",
  transactionType: "",
  ownershipType: "",
  bedroomsImages: [],
  bathroomsImages: [],
  exteriorViewImages: [],
  kitchenImages: [],
  floorPlanImages: [],
  facing: "",
  facingRoadWidth: "",
  facingWidthType: "Ft",
  farmhouseStatus : "Ready to Move",
  landmark : ""
};
